version: '3'

volumes:
  db:

services:
  bot:
    image: lootbot
    command: lootbot --migrate -vvv
    env_file: .env
    environment:
      connection: postgresql+psycopg2://lootbot:lootbot_password@db:5432/lootbot

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: lootbot
      POSTGRES_PASSWORD: lootbot_password
      POSTGRES_DB: lootbot
    volumes:
      - db:/var/lib/postgresql/data
